# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quant-network 
  template:
    metadata:
      labels:
        app: quant-network
    spec:
      containers:
      - name: quant-network
        image: syedusman/quant-network
        ports:
        - containerPort: 80

