
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quant-network-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quant-network-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 20  # Adjust as necessary
