apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: quant-network-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment
  minReplicas: 1
  maxReplicas: 10  # Adjust this based on your needs
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale when CPU usage exceeds 50%
